In [ ]:
import pandas as pd

In [ ]:
dataset=pd.read_csv("/content/50_Startups.csv")

In [ ]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
dataset=pd.get_dummies(dataset)

In [ ]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0

In [ ]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [ ]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0

In [ ]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_California', 'State_Florida', 'State_New York'],
      dtype='object')

In [ ]:
dependent=dataset[["Profit"]]

In [ ]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_California', 'State_Florida']]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
weight=regressor.coef_
weight

array([[ 7.90840255e-01,  3.01968165e-02,  3.10148566e-02,
        -3.04799573e+02,  1.58229418e+02]])

In [ ]:
bias=regressor.intercept_
bias

array([42708.67044388])

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [ ]:
r_score

0.9358680970044478

In [ ]:
import pickle
filename="finalized_model_Mul_linear.sav"
pickle.dump(regressor,open(filename,'wb'))

In [ ]:
loaded_model=pickle.load(open("finalized_model_Mul_linear.sav",'rb'))
result=loaded_model.predict([[1234,345,4565,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
result

array([[43531.76846711]])